### PR TITLE
buffer-reverse

### PR DESCRIPTION
**Pull request by fanatid**
Related issue: #11
for you information, tests fails even with iojs: https://travis-ci.org/fanatid/blockchain-spv/builds/115241699

### CODE REVIEW

**Comment by mappum** [comment]
To fix the errors caused by `Object.assign`, I can set up babel builds (I was planning on using some other ES6 features to make the code a little cleaner).

**Comment by fanatid** [comment]
maybe better drop iojs and node 0.12 support?

**Comment by mappum** [comment]
I'm fine with only supporting node >= 4, but we will have to ensure compatibility with browsers that don't support ES6.

**Comment by fanatid** [comment]
agree, supports browsers even harder than supports different node versions

**Comment by fanatid** [comment]
any things that I should fix before you merging this PR?

**Comment by mappum** [comment]
LGTM.

I was not aware that `util.inherits` has issues in browsers. Just wondering, what is the issue?

**Comment by fanatid** [comment]
@mappum I also wanted to ask you, why you mix `tape` and `tap`?

**Comment by mappum** [comment]
That's just because I was trying to convert to `tap` for the coverage tools, but it does not support `t.plan()` and I would have had to rewrite some tests.

**Comment by fanatid** [comment]
issue with `util.inherits` is same that with `crypto.createHash` :)
we don't need whole `util` package (browser version of `util` uses `inherits`)

**Comment by fanatid** [comment]
oh, I see, it's awful that `tap` doesn't support `t.plan`!
did you try AVA? if you don't need run test code in browser it's better choice, IMO

**Comment by fanatid** [comment]
@mappum I tried `tape` with `nyc` and looks all works fine :)
https://github.com/fanatid/xorshift.js/blob/b7d9e918905ea774b88b1c216cc4f86984619230/package.json#L34

**Pull request merged**
